default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.3'
    hooks:
      - id: poetry-check
  - repo: local
    hooks:
      - id: static-analysis
        name: ruff-linter
        entry: poetry run ruff check
        language: system
        pass_filenames: true
        types:
          - python
        args:
          - '--config=./pyproject.toml'
          - '--fix'
      - id: format
        name: ruff-format
        entry: poetry run ruff format
        language: system
        pass_filenames: true
        types:
          - python
        args:
          - '--config=./pyproject.toml'
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [ push ]
